SET SCHEMA hybench1x_column;

CREATE TABLE customer (
custID int,
companyID int,
gender varchar(6),
name varchar(15),
age int,
phone varchar(11),
province varchar(15),
city varchar(15),
loan_balance decimal(15,2),
saving_credit int,
checking_credit int,
loan_credit int,
Isblocked int,
created_date timestamp,
last_update_timestamp timestamp default current_timestamp,
primary key(custid)
);

CREATE TABLE company (
companyID int,
name varchar(50),
category varchar(50),
staff_size int,
loan_balance real,
phone char(11),
province char(15),
city char(15),
saving_credit int,
checking_credit int,
loan_credit int,
Isblocked int,
created_date timestamp,
last_update_timestamp timestamp,
PRIMARY KEY(companyID)
);

CREATE TABLE savingAccount (
 accountID int,
 userID int,
 balance real,
 Isblocked int,
 savingAccount_ts timestamp,
 PRIMARY KEY(accountID)
);


CREATE TABLE checkingAccount (
accountID int,
userID int,
balance real,
Isblocked int,
checkingAccount_ts timestamp,
PRIMARY KEY(accountID)
);

CREATE TABLE transfer (
  id int GENERATED BY DEFAULT AS IDENTITY,
  sourceID int,
  targetID int,
  amount real,
  type char(10),
  transfer_ts timestamp,
  fresh_ts timestamp  default current_timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE checking (
  id int GENERATED BY DEFAULT AS IDENTITY,
  sourceID int,
  targetID int,
  amount real,
  type char(10),
  checking_ts timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE loanapps (
  id int GENERATED BY DEFAULT AS IDENTITY,
  applicantID int,
  amount real,
  duration int,
  status char(12),
  loanapps_ts timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE loantrans (
  id int GENERATED BY DEFAULT AS IDENTITY,
  applicantID int,
  appID int,
  amount real,
  status char(12),
  loantrans_ts timestamp,
  duration int,
  contract_timestamp timestamp,
  delinquency int,
  PRIMARY KEY(id)
);
