CREATE SEQUENCE TRANSFER_SEQ INCREMENT BY 1 START WITH SF1_NUM;

CREATE SEQUENCE CHECKING_SEQ INCREMENT BY 1 START WITH SF1_NUM;

CREATE SEQUENCE LOANAPPS_SEQ INCREMENT BY 1 START WITH SF1_NUM;

CREATE SEQUENCE LOANTRANS_SEQ INCREMENT BY 1 START WITH SF1_NUM;