SET SCHEMA HYBENCH1X;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/customer.csv'
    INTO HYBENCH1X.customer
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/company.csv'
    INTO HYBENCH1X.company
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/savingAccount.csv'
    INTO HYBENCH1X.savingaccount
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/checkingAccount.csv'
    INTO HYBENCH1X.checkingaccount
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/checking.csv'
    INTO HYBENCH1X.checking
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/loanApps.csv'
    INTO HYBENCH1X.loanapps
    WITH THREADS 10
    BATCH 50000
    RECORD DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/loanTrans.csv'
    INTO HYBENCH1X.loantrans
    WITH THREADS 10
    BATCH 50000 RECORD
    DELIMITED BY '\n'
    FIELD DELIMITED BY ','
    OPTIONALLY ENCLOSED BY '"'
    TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
    ERROR LOG 'error_log.txt'
;

IMPORT FROM CSV FILE '/hana/mounts/Data_1x/transfer.csv'
   INTO HYBENCH1X.transfer
   WITH THREADS 10
   BATCH 50000 RECORD
   DELIMITED BY '\n'
   FIELD DELIMITED BY ','
   OPTIONALLY ENCLOSED BY '"'
   TIMESTAMP FORMAT 'YYYY-MM-DD HH24:MI:SS.FF3'
   ERROR LOG 'error_log.txt';


